### Obtener solo los postres de todos los menús
GET http://localhost:1337/menus/postres
Accept: application/json

### Filtrar menús por rango de precios
GET http://localhost:1337/menus?min_precio=100&max_precio=185
Accept: application/json

### Filtrar menús sin ciertos alérgenos (GET /menus?excluir_alergenos=gluten,lactosa).
GET http://localhost:1337/menus/filtrar?excluir_alergenos=Pescado,Pimienta
Accept: application/json

### Obtener los platos más populares
GET http://localhost:1337/platos/populares?min_apariciones=3
Accept: application/json